KeyError
Python 3.6.5: /usr/bin/python3
Thu Jul  9 16:06:49 2020

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /home/minming/Desktop/.PIXIV/Main_Pixiv.py in <lambda>()
 1166         if flag != '用户':
 1167             self.infoFrame.moreButton.clicked.connect(
 1168                 lambda: self.show_pic(self.method, self.next_url_s[title], title, flag=flag))
 1169         else:
 1170             self.infoFrame.moreButton.clicked.connect(lambda: self._search(self.next_url_s[title], title))
self = <__main__.main_pixiv object>
self.show_pic = <bound method main_pixiv.show_pic of <__main__.main_pixiv object>>
self.method = ''
self.next_url_s = {'推荐': {'content_type': 'illust', 'filter': 'for_ios', 'include_privacy_policy': 'false', 'include_ranking_illusts': 'false', 'include_ranking_label': 'true', 'max_bookmark_id_for_recommend': '7880523403', 'min_bookmark_id_for_recent_illust': '8532756717', 'offset': '0'}, '标签:starbound': {'filter': 'for_ios', 'offset': '30', 'search_target': 'partial_match_for_tags', 'sort': 'date_desc', 'word': 'starbound'}}
title = '标签:starbound'
flag = '标签作品'

 /home/minming/Desktop/.PIXIV/Main_Pixiv.py in show_pic(self=<__main__.main_pixiv object>, method='', _mode={'filter': 'for_ios', 'offset': '30', 'search_target': 'partial_match_for_tags', 'sort': 'date_desc', 'word': 'starbound'}, title='标签:starbound', isMoreButton=True, flag='标签作品')
  453             self.baseThread['get_img_info'].start()
  454         else:
  455             self.parse_pic_info({"title": title})
  456 
  457     def parse_pic_info(self, ranking={}):
self = <__main__.main_pixiv object>
self.parse_pic_info = <bound method main_pixiv.parse_pic_info of <__main__.main_pixiv object>>
title = '标签:starbound'

 /home/minming/Desktop/.PIXIV/Main_Pixiv.py in parse_pic_info(self=<__main__.main_pixiv object>, ranking={'title': '标签:starbound'})
  462             return
  463         if 'next_url' not in ranking:
  464             ranking = self.add_key_to_result(ranking)
  465             print(ranking)
  466 
ranking = {'title': '标签:starbound'}
self = <__main__.main_pixiv object>
self.add_key_to_result = <bound method main_pixiv.add_key_to_result of <__main__.main_pixiv object>>

 /home/minming/Desktop/.PIXIV/Main_Pixiv.py in add_key_to_result(self=<__main__.main_pixiv object>, ranking={'title': '标签:starbound'}, info={})
  634 
  635     def add_key_to_result(self, ranking, info={}):
  636         illusts = [ranking['illust']]
  637         info['illusts'] = illusts
  638         info['next_url'] = None
illusts undefined
ranking = {'title': '标签:starbound'}
KeyError: 'illust'
    __cause__ = None
    __class__ = <class 'KeyError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of KeyError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of KeyError object>
    __doc__ = 'Mapping key not found.'
    __eq__ = <method-wrapper '__eq__' of KeyError object>
    __format__ = <built-in method __format__ of KeyError object>
    __ge__ = <method-wrapper '__ge__' of KeyError object>
    __getattribute__ = <method-wrapper '__getattribute__' of KeyError object>
    __gt__ = <method-wrapper '__gt__' of KeyError object>
    __hash__ = <method-wrapper '__hash__' of KeyError object>
    __init__ = <method-wrapper '__init__' of KeyError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of KeyError object>
    __lt__ = <method-wrapper '__lt__' of KeyError object>
    __ne__ = <method-wrapper '__ne__' of KeyError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of KeyError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of KeyError object>
    __repr__ = <method-wrapper '__repr__' of KeyError object>
    __setattr__ = <method-wrapper '__setattr__' of KeyError object>
    __setstate__ = <built-in method __setstate__ of KeyError object>
    __sizeof__ = <built-in method __sizeof__ of KeyError object>
    __str__ = <method-wrapper '__str__' of KeyError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ('illust',)
    with_traceback = <built-in method with_traceback of KeyError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "./Main_Pixiv.py", line 1168, in <lambda>
    lambda: self.show_pic(self.method, self.next_url_s[title], title, flag=flag))
  File "./Main_Pixiv.py", line 455, in show_pic
    self.parse_pic_info({"title": title})
  File "./Main_Pixiv.py", line 464, in parse_pic_info
    ranking = self.add_key_to_result(ranking)
  File "./Main_Pixiv.py", line 636, in add_key_to_result
    illusts = [ranking['illust']]
KeyError: 'illust'

