AttributeError
Python 3.6.5: /usr/bin/python3.6
Tue Jun 30 18:01:59 2020

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /home/minming/Desktop/.PIXIV/Pixiv_Widget/Info_Frame.py in load_user_head(self=<Pixiv_Widget.Info_Frame.info_frame object>, info={'file_name': 'user_70435_pic', 'isSuccess': False, 'row': 1022, 'url': 'https://i.pximg.net/user-profile/img/2010/08/17/.../2093736_d35b7c3ac5058fb8804ae32ec2763eed_170.png'})
  196             file = f"{temp_path}/{file_name}"
  197         else:
  198             file = self.timeout_pic
  199         print(file)
  200         try:
file undefined
self = <Pixiv_Widget.Info_Frame.info_frame object>
self.timeout_pic undefined
AttributeError: 'info_frame' object has no attribute 'timeout_pic'
    __cause__ = None
    __class__ = <class 'AttributeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of AttributeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of AttributeError object>
    __doc__ = 'Attribute not found.'
    __eq__ = <method-wrapper '__eq__' of AttributeError object>
    __format__ = <built-in method __format__ of AttributeError object>
    __ge__ = <method-wrapper '__ge__' of AttributeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of AttributeError object>
    __gt__ = <method-wrapper '__gt__' of AttributeError object>
    __hash__ = <method-wrapper '__hash__' of AttributeError object>
    __init__ = <method-wrapper '__init__' of AttributeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of AttributeError object>
    __lt__ = <method-wrapper '__lt__' of AttributeError object>
    __ne__ = <method-wrapper '__ne__' of AttributeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of AttributeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of AttributeError object>
    __repr__ = <method-wrapper '__repr__' of AttributeError object>
    __setattr__ = <method-wrapper '__setattr__' of AttributeError object>
    __setstate__ = <built-in method __setstate__ of AttributeError object>
    __sizeof__ = <built-in method __sizeof__ of AttributeError object>
    __str__ = <method-wrapper '__str__' of AttributeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("'info_frame' object has no attribute 'timeout_pic'",)
    with_traceback = <built-in method with_traceback of AttributeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/home/minming/Desktop/.PIXIV/Pixiv_Widget/Info_Frame.py", line 198, in load_user_head
    file = self.timeout_pic
AttributeError: 'info_frame' object has no attribute 'timeout_pic'

